//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARKBreedingStats.local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARKBreedingStats.local.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about….
        /// </summary>
        internal static string aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string added {
            get {
                return ResourceManager.GetString("added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a creature in your library that has all the available top-stats ({0} {1}).
        ///The currently selected conservative-breeding-mode might show some suggestions that may seem non-optimal.
        ///Change the breeding-mode to &quot;High Stats&quot; for better suggestions..
        /// </summary>
        internal static string AlreadyCreatureWithTopStats {
            get {
                return ResourceManager.GetString("AlreadyCreatureWithTopStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is approx. one Narcoberry every.
        /// </summary>
        internal static string ApproxOneNarcoberryEvery {
            get {
                return ResourceManager.GetString("ApproxOneNarcoberryEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby.
        /// </summary>
        internal static string Baby {
            get {
                return ResourceManager.GetString("Baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Possible.
        /// </summary>
        internal static string BestPossible {
            get {
                return ResourceManager.GetString("BestPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus-Level.
        /// </summary>
        internal static string BonusLevel {
            get {
                return ResourceManager.GetString("BonusLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        internal static string Bow {
            get {
                return ResourceManager.GetString("Bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or mutations.
        /// </summary>
        internal static string BPorMutations {
            get {
                return ResourceManager.GetString("BPorMutations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some creatures are filtered out due to their mutations.
        /// </summary>
        internal static string BPsomeCreaturesAreFilteredOutMutations {
            get {
                return ResourceManager.GetString("BPsomeCreaturesAreFilteredOutMutations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some creatures are filtered out due to their tags.
        /// </summary>
        internal static string BPsomeCreaturesAreFilteredOutTags {
            get {
                return ResourceManager.GetString("BPsomeCreaturesAreFilteredOutTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The top-stats shown here might not be the top-stats of your entire library..
        /// </summary>
        internal static string BPTopStatsShownMightNotTotalTopStats {
            get {
                return ResourceManager.GetString("BPTopStatsShownMightNotTotalTopStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bred.
        /// </summary>
        internal static string bred {
            get {
                return ResourceManager.GetString("bred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeding not possible.
        /// </summary>
        internal static string BreedingNotPossible {
            get {
                return ResourceManager.GetString("BreedingNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeding Plan.
        /// </summary>
        internal static string BreedingPlan {
            get {
                return ResourceManager.GetString("BreedingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeding Plan….
        /// </summary>
        internal static string BreedingPlanHelpToolStripMenuItem {
            get {
                return ResourceManager.GetString("BreedingPlanHelpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeding Value.
        /// </summary>
        internal static string breedingValue {
            get {
                return ResourceManager.GetString("breedingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new to Library.
        /// </summary>
        internal static string btAdd2Library {
            get {
                return ResourceManager.GetString("btAdd2Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add Wake-up-Timer.
        /// </summary>
        internal static string btAddWakeUpTimer {
            get {
                return ResourceManager.GetString("btAddWakeUpTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply new Weightings.
        /// </summary>
        internal static string btBPApplyNewWeights {
            get {
                return ResourceManager.GetString("btBPApplyNewWeights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These Parents just mated.
        /// </summary>
        internal static string btBPJustMated {
            get {
                return ResourceManager.GetString("btBPJustMated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create an incubation-entry in the Raising-tab.
        /// </summary>
        internal static string btBPJustMatedTT {
            get {
                return ResourceManager.GetString("btBPJustMatedTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to clear all color-regions..
        /// </summary>
        internal static string btClearColorsTT {
            get {
                return ResourceManager.GetString("btClearColorsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Level Distribution.
        /// </summary>
        internal static string btExtractLevels {
            get {
                return ResourceManager.GetString("btExtractLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Export.
        /// </summary>
        internal static string btImportLastExported {
            get {
                return ResourceManager.GetString("btImportLastExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import the creature-file that was exported last (ingame with the &quot;Export Data&quot;-function.
        /// </summary>
        internal static string btImportLastExportedTT {
            get {
                return ResourceManager.GetString("btImportLastExportedTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add Starving-Timer.
        /// </summary>
        internal static string btnAddStarvingTimer {
            get {
                return ResourceManager.GetString("btnAddStarvingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate automatic name
        ///Right-click to edit the pattern..
        /// </summary>
        internal static string btnGenerateUniqueNameTT {
            get {
                return ResourceManager.GetString("btnGenerateUniqueNameTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Values from ARK Window.
        /// </summary>
        internal static string btReadValuesFromArk {
            get {
                return ResourceManager.GetString("btReadValuesFromArk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfom an OCR on the opened inventory of a creature ingame.
        ///To use this feature you have to enable OCR in the settings and load a ocr-config-file which is made for your screen-resolution in the OCR-tab..
        /// </summary>
        internal static string btReadValuesFromArkTT {
            get {
                return ResourceManager.GetString("btReadValuesFromArkTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string btSaveChanges {
            get {
                return ResourceManager.GetString("btSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0.
        /// </summary>
        internal static string C0 {
            get {
                return ResourceManager.GetString("C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1.
        /// </summary>
        internal static string C1 {
            get {
                return ResourceManager.GetString("C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2.
        /// </summary>
        internal static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3.
        /// </summary>
        internal static string C3 {
            get {
                return ResourceManager.GetString("C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C4.
        /// </summary>
        internal static string C4 {
            get {
                return ResourceManager.GetString("C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C5.
        /// </summary>
        internal static string C5 {
            get {
                return ResourceManager.GetString("C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if all creatures should be excluded and only be included when have the include-mark on their tag.
        ///If this checkbox is unchecked, all creatures will be included by default, and only excluded if one of their tags has the exclude-mark and none has the include-mark..
        /// </summary>
        internal static string cbBPTagExcludeDefaultTT {
            get {
                return ResourceManager.GetString("cbBPTagExcludeDefaultTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly, don&apos;t adjust.
        /// </summary>
        internal static string cbExactlyImprinting {
            get {
                return ResourceManager.GetString("cbExactlyImprinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this if you have exactly 100% imprinting..
        /// </summary>
        internal static string cbExactlyImprintingTT {
            get {
                return ResourceManager.GetString("cbExactlyImprintingTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess Species.
        /// </summary>
        internal static string cbGuessSpecies {
            get {
                return ResourceManager.GetString("cbGuessSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the tool will try to guess the species after reading the values from ARK with OCR.
        ///If the tool recognizes the species-name it will take that, otherwise it will check if the stat-values match a certain species.
        ///
        ///Uncheck this if the tool repeatedly selects the wrong species after OCR (you have to choose it manually then)..
        /// </summary>
        internal static string cbGuessSpeciesTT {
            get {
                return ResourceManager.GetString("cbGuessSpeciesTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Wild-Creature Check.
        /// </summary>
        internal static string cbQuickWildCheck {
            get {
                return ResourceManager.GetString("cbQuickWildCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this if you just want a quick check of the levels of a wild (untamed) creature.
        ///The levels are then shown without the extraction-process (and without validation)..
        /// </summary>
        internal static string cbQuickWildCheckTT {
            get {
                return ResourceManager.GetString("cbQuickWildCheckTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string cbToggleOverlay {
            get {
                return ResourceManager.GetString("cbToggleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch Capacity.
        /// </summary>
        internal static string ChargeCapacity {
            get {
                return ResourceManager.GetString("ChargeCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        internal static string ChargeCapacity_Abb {
            get {
                return ResourceManager.GetString("ChargeCapacity_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch Emission Range.
        /// </summary>
        internal static string ChargeEmissionRange {
            get {
                return ResourceManager.GetString("ChargeEmissionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRa.
        /// </summary>
        internal static string ChargeEmissionRange_Abb {
            get {
                return ResourceManager.GetString("ChargeEmissionRange_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch Regen.
        /// </summary>
        internal static string ChargeRegeneration {
            get {
                return ResourceManager.GetString("ChargeRegeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRe.
        /// </summary>
        internal static string ChargeRegeneration_Abb {
            get {
                return ResourceManager.GetString("ChargeRegeneration_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string checkForUpdatedStatsToolStripMenuItem {
            get {
                return ResourceManager.GetString("checkForUpdatedStatsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Creatures with Cooldown.
        /// </summary>
        internal static string cnBPIncludeCooldowneds {
            get {
                return ResourceManager.GetString("cnBPIncludeCooldowneds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooldown.
        /// </summary>
        internal static string cooldown {
            get {
                return ResourceManager.GetString("cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooldown/Growing.
        /// </summary>
        internal static string cooldownGrowing {
            get {
                return ResourceManager.GetString("cooldownGrowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Creature.
        /// </summary>
        internal static string copyCreatureToolStripMenuItem {
            get {
                return ResourceManager.GetString("copyCreatureToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to MultiplierTester.
        /// </summary>
        internal static string copyToMultiplierTesterToolStripButton {
            get {
                return ResourceManager.GetString("copyToMultiplierTesterToolStripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the levels, TE and IB from the Tester, and the stat-values from the Extractor will be copied to the Stat-Multiplier-Tester.
        /// </summary>
        internal static string copyToMultiplierTesterToolStripButtonTT {
            get {
                return ResourceManager.GetString("copyToMultiplierTesterToolStripButtonTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature.
        /// </summary>
        internal static string Creature {
            get {
                return ResourceManager.GetString("Creature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossbow.
        /// </summary>
        internal static string Crossbow {
            get {
                return ResourceManager.GetString("Crossbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current stat-value.
        /// </summary>
        internal static string currentStatValue {
            get {
                return ResourceManager.GetString("currentStatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value.
        /// </summary>
        internal static string currentValue {
            get {
                return ResourceManager.GetString("currentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dm.
        /// </summary>
        internal static string Damage_Abb {
            get {
                return ResourceManager.GetString("Damage_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Creatures.
        /// </summary>
        internal static string deadCreaturesToolStripMenuItem {
            get {
                return ResourceManager.GetString("deadCreaturesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove….
        /// </summary>
        internal static string deleteSelectedToolStripMenuItem {
            get {
                return ResourceManager.GetString("deleteSelectedToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domesticated at.
        /// </summary>
        internal static string domesticatedAt {
            get {
                return ResourceManager.GetString("domesticatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels assigned manually to this stat after the creature was domesticated.
        /// </summary>
        internal static string domLevelExplanation {
            get {
                return ResourceManager.GetString("domLevelExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dom-Lvl.
        /// </summary>
        internal static string domLvl {
            get {
                return ResourceManager.GetString("domLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string editToolStripMenuItem {
            get {
                return ResourceManager.GetString("editToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg.
        /// </summary>
        internal static string Egg {
            get {
                return ResourceManager.GetString("Egg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Prod.
        /// </summary>
        internal static string ElectricProd {
            get {
                return ResourceManager.GetString("ElectricProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Prod Hits.
        /// </summary>
        internal static string ElectricProdHits {
            get {
                return ResourceManager.GetString("ElectricProdHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event_ {
            get {
                return ResourceManager.GetString("Event_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Clipboard.
        /// </summary>
        internal static string exportValuesToClipboardToolStripMenuItem {
            get {
                return ResourceManager.GetString("exportValuesToClipboardToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction Issues….
        /// </summary>
        internal static string extractionIssuesToolStripMenuItem {
            get {
                return ResourceManager.GetString("extractionIssuesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extractor.
        /// </summary>
        internal static string extractor {
            get {
                return ResourceManager.GetString("extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        internal static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Females.
        /// </summary>
        internal static string femalesToolStripMenuItem {
            get {
                return ResourceManager.GetString("femalesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Duplicates….
        /// </summary>
        internal static string findDuplicatesToolStripMenuItem {
            get {
                return ResourceManager.GetString("findDuplicatesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished at.
        /// </summary>
        internal static string FinishedAt {
            get {
                return ResourceManager.GetString("FinishedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fo.
        /// </summary>
        internal static string Food_Abb {
            get {
                return ResourceManager.GetString("Food_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food has to drop by {0} units..
        /// </summary>
        internal static string FoodHasToDropUnits {
            get {
                return ResourceManager.GetString("FoodHasToDropUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeding-Mode.
        /// </summary>
        internal static string gbBPBreedingMode {
            get {
                return ResourceManager.GetString("gbBPBreedingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offspring.
        /// </summary>
        internal static string gbBPOffspring {
            get {
                return ResourceManager.GetString("gbBPOffspring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature-info.
        /// </summary>
        internal static string gbCreatureInfo {
            get {
                return ResourceManager.GetString("gbCreatureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knockout Info.
        /// </summary>
        internal static string gbKOInfo {
            get {
                return ResourceManager.GetString("gbKOInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Damage [%].
        /// </summary>
        internal static string gbWeaponDamage {
            get {
                return ResourceManager.GetString("gbWeaponDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gen.
        /// </summary>
        internal static string Generation_Abb {
            get {
                return ResourceManager.GetString("Generation_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview / Edit.
        /// </summary>
        internal static string gpPreviewEdit {
            get {
                return ResourceManager.GetString("gpPreviewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starving-Time.
        /// </summary>
        internal static string gpStarvingTime {
            get {
                return ResourceManager.GetString("gpStarvingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpor-Time.
        /// </summary>
        internal static string gpTorporTime {
            get {
                return ResourceManager.GetString("gpTorporTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grown in.
        /// </summary>
        internal static string grownIn {
            get {
                return ResourceManager.GetString("grownIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP.
        /// </summary>
        internal static string Health_Abb {
            get {
                return ResourceManager.GetString("Health_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string helpToolStripMenuItem {
            get {
                return ResourceManager.GetString("helpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immobilized by.
        /// </summary>
        internal static string ImmobilizedBy {
            get {
                return ResourceManager.GetString("ImmobilizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import created json-file….
        /// </summary>
        internal static string importCreatedJsonfileToolStripMenuItem {
            get {
                return ResourceManager.GetString("importCreatedJsonfileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import exported Creatures.
        /// </summary>
        internal static string importExportedCreaturesToolStripMenuItem {
            get {
                return ResourceManager.GetString("importExportedCreaturesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing from ARK-Tools.
        /// </summary>
        internal static string importingFromARKToolsToolStripMenuItem {
            get {
                return ResourceManager.GetString("importingFromARKToolsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Values from Clipboard.
        /// </summary>
        internal static string importValuesFromClipboardToolStripMenuItem {
            get {
                return ResourceManager.GetString("importValuesFromClipboardToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprinting Bonus.
        /// </summary>
        internal static string imprintingBonus {
            get {
                return ResourceManager.GetString("imprintingBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extraction is potentially possible, but it seems the max wild level is set too low for a valid extraction. Check if you set the correct value in the settings.
        ///The current value is {0} and this creature seems to have a higher wild level than this.
        ///
        ///For other reasons of the failing of the extraction, see the list on the right after closing this messagebox..
        /// </summary>
        internal static string issueMaxWildLevelTooLow {
            get {
                return ResourceManager.GetString("issueMaxWildLevelTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeding Score.
        /// </summary>
        internal static string lbBPBreedingScore {
            get {
                return ResourceManager.GetString("lbBPBreedingScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Breeding-Score of a paring is not comparable to the Breeding-Score of another breeding-mode.
        ///The numbers in the different modes are generated in incompatible ways..
        /// </summary>
        internal static string lbBPBreedingScoreTT {
            get {
                return ResourceManager.GetString("lbBPBreedingScoreTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeding Times.
        /// </summary>
        internal static string lbBPBreedingTimes {
            get {
                return ResourceManager.GetString("lbBPBreedingTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Torpor.
        /// </summary>
        internal static string lbCurrentTorpor {
            get {
                return ResourceManager.GetString("lbCurrentTorpor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cuddles given to get to this Imprinting-Bonus.
        ///Click left to set to the closest valid integer.
        ///Click right to set the imprinting to the value so for the torpor the levels in the tester and the value in the extractor match..
        /// </summary>
        internal static string lbImprintedCountTT {
            get {
                return ResourceManager.GetString("lbImprintedCountTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cuddles given to get to this Imprinting-Bonus..
        /// </summary>
        internal static string lbImprintingCuddleCountExtractorTT {
            get {
                return ResourceManager.GetString("lbImprintingCuddleCountExtractorTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red: listening, grey: deactivated, green: recognized, orange: didn&apos;t recognized
        ///Say &quot;[species] [level]&quot;, e.g. &quot;Rex level 30&quot; or &quot;Brontosaurus 50&quot;
        ///to get taming-infos in the overlay.
        /// </summary>
        internal static string lbListeningTT {
            get {
                return ResourceManager.GetString("lbListeningTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        internal static string lbMax {
            get {
                return ResourceManager.GetString("lbMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy the name to the clipboard, e.g. for pasting it in the game..
        /// </summary>
        internal static string lbNameTT {
            get {
                return ResourceManager.GetString("lbNameTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Creature is not yet tamed and may get better values then..
        /// </summary>
        internal static string lbNotYetTamed {
            get {
                return ResourceManager.GetString("lbNotYetTamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle if the OCR can change the owner-field.
        ///Enable it if the OCR doesn&apos;t recognize the owner-name correctly and you want to add multiple creatures with the same owner..
        /// </summary>
        internal static string lbOwnerTT {
            get {
                return ResourceManager.GetString("lbOwnerTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a creature in the Library to see its pedigree here..
        /// </summary>
        internal static string lbPedigreeEmpty {
            get {
                return ResourceManager.GetString("lbPedigreeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be.
        /// </summary>
        internal static string lbShouldBe {
            get {
                return ResourceManager.GetString("lbShouldBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string lbSum {
            get {
                return ResourceManager.GetString("lbSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the number that the sum of all manual levelups should be equal to..
        /// </summary>
        internal static string lbSumDomSBTT {
            get {
                return ResourceManager.GetString("lbSumDomSBTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the sum of all manual levelups of this creature, it should exactly match the number below.
        ///If it&apos;s not matching, click on a stat that is yellow and choose another possible level distribution..
        /// </summary>
        internal static string lbSumDomTT {
            get {
                return ResourceManager.GetString("lbSumDomTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an indicator if the sum of the wild levels is valid.
        ///If a number with a plus sign is shown, the sum is too high and you need to choose another possibility from the lists of yellow stats..
        /// </summary>
        internal static string lbSumWildTT {
            get {
                return ResourceManager.GetString("lbSumWildTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taming time.
        /// </summary>
        internal static string lbTamingTime {
            get {
                return ResourceManager.GetString("lbTamingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview or edit levels of a creature..
        /// </summary>
        internal static string lbTestingInfo {
            get {
                return ResourceManager.GetString("lbTestingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time until wake-up: {0}.
        /// </summary>
        internal static string lbTimeUntilWakingUp {
            get {
                return ResourceManager.GetString("lbTimeUntilWakingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle if the OCR can change the tribe-field.
        ///Enable it if the OCR doesn&apos;t recognize the tribe-name correctly and you want to add multiple creatures with the same tribe..
        /// </summary>
        internal static string lbTribeTT {
            get {
                return ResourceManager.GetString("lbTribeTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to used.
        /// </summary>
        internal static string lbUsed {
            get {
                return ResourceManager.GetString("lbUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl.
        /// </summary>
        internal static string Level_Abb {
            get {
                return ResourceManager.GetString("Level_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LW.
        /// </summary>
        internal static string LevelWild_Abb {
            get {
                return ResourceManager.GetString("LevelWild_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string library {
            get {
                return ResourceManager.GetString("library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load additional values….
        /// </summary>
        internal static string loadAdditionalValuesToolStripMenuItem {
            get {
                return ResourceManager.GetString("loadAdditionalValuesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load and A&amp;dd....
        /// </summary>
        internal static string loadAndAddToolStripMenuItem {
            get {
                return ResourceManager.GetString("loadAndAddToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Load....
        /// </summary>
        internal static string loadToolStripMenuItem {
            get {
                return ResourceManager.GetString("loadToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longneck.
        /// </summary>
        internal static string Longneck {
            get {
                return ResourceManager.GetString("Longneck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Males.
        /// </summary>
        internal static string malesToolStripMenuItem {
            get {
                return ResourceManager.GetString("malesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturation.
        /// </summary>
        internal static string Maturation {
            get {
                return ResourceManager.GetString("Maturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        internal static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiSetter….
        /// </summary>
        internal static string multiSetterToolStripMenuItem {
            get {
                return ResourceManager.GetString("multiSetterToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutated Creatures.
        /// </summary>
        internal static string mutatedCreaturesToolStripMenuItem {
            get {
                return ResourceManager.GetString("mutatedCreaturesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutation-Counter.
        /// </summary>
        internal static string mutationCounter {
            get {
                return ResourceManager.GetString("mutationCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutations.
        /// </summary>
        internal static string Mutations {
            get {
                return ResourceManager.GetString("Mutations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mu.
        /// </summary>
        internal static string Mutations_Abb {
            get {
                return ResourceManager.GetString("Mutations_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narcotics.
        /// </summary>
        internal static string Narcotics {
            get {
                return ResourceManager.GetString("Narcotics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a yet.
        /// </summary>
        internal static string naYet {
            get {
                return ResourceManager.GetString("naYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        internal static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutered.
        /// </summary>
        internal static string Neutered {
            get {
                return ResourceManager.GetString("Neutered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutered Creatures.
        /// </summary>
        internal static string neuteredCreaturesToolStripMenuItem {
            get {
                return ResourceManager.GetString("neuteredCreaturesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Library.
        /// </summary>
        internal static string newToolStripMenuItem {
            get {
                return ResourceManager.GetString("newToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No possible pairings found for {0}. Make sure at least one female and male are available in your library and that you didn&apos;t exclude all possible creatures via the tag-selector..
        /// </summary>
        internal static string NoPossiblePairingForSpeciesFound {
            get {
                return ResourceManager.GetString("NoPossiblePairingForSpeciesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no taming-data available.
        /// </summary>
        internal static string noTamingData {
            get {
                return ResourceManager.GetString("noTamingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available.
        /// </summary>
        internal static string notAvailable {
            get {
                return ResourceManager.GetString("notAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough food to tame the creature!.
        /// </summary>
        internal static string notEnoughFoodToTame {
            get {
                return ResourceManager.GetString("notEnoughFoodToTame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not yet tamed.
        /// </summary>
        internal static string notYetTamed {
            get {
                return ResourceManager.GetString("notYetTamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider only creatures with at most this many mutations.
        ///Set to -1 for any number of mutation..
        /// </summary>
        internal static string nudBPMutationLimitTT {
            get {
                return ResourceManager.GetString("nudBPMutationLimitTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obelisk Creatures.
        /// </summary>
        internal static string obeliskCreaturesToolStripMenuItem {
            get {
                return ResourceManager.GetString("obeliskCreaturesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Manual….
        /// </summary>
        internal static string onlinehelpToolStripMenuItem {
            get {
                return ResourceManager.GetString("onlinehelpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only pairings with &quot;{0}&quot;.
        /// </summary>
        internal static string onlyPairingsWith {
            get {
                return ResourceManager.GetString("onlyPairingsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or one Bio Toxin every.
        /// </summary>
        internal static string OrOneBioToxinEvery {
            get {
                return ResourceManager.GetString("OrOneBioToxinEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or one Narcotic every.
        /// </summary>
        internal static string OrOneNarcoticEvery {
            get {
                return ResourceManager.GetString("OrOneNarcoticEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygen.
        /// </summary>
        internal static string Oxygen {
            get {
                return ResourceManager.GetString("Oxygen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ox.
        /// </summary>
        internal static string Oxygen_Abb {
            get {
                return ResourceManager.GetString("Oxygen_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Creature.
        /// </summary>
        internal static string pasteCreatureToolStripMenuItem {
            get {
                return ResourceManager.GetString("pasteCreatureToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedigree.
        /// </summary>
        internal static string pedigree {
            get {
                return ResourceManager.GetString("pedigree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability for this Best Possible outcome.
        /// </summary>
        internal static string ProbabilityForBest {
            get {
                return ResourceManager.GetString("ProbabilityForBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string quitToolStripMenuItem {
            get {
                return ResourceManager.GetString("quitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raising.
        /// </summary>
        internal static string Raising {
            get {
                return ResourceManager.GetString("Raising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Stats.
        /// </summary>
        internal static string rbBPHighStats {
            get {
                return ResourceManager.GetString("rbBPHighStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for best next-generation-results.
        ///The chance for an overall good creature is better.
        ///Check if it&apos;s not important to have a Top-Stats-Offspring..
        /// </summary>
        internal static string rbBPHighStatsTT {
            get {
                return ResourceManager.GetString("rbBPHighStatsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Stats Lc.
        /// </summary>
        internal static string rbBPTopStats {
            get {
                return ResourceManager.GetString("rbBPTopStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Stats Cn.
        /// </summary>
        internal static string rbBPTopStatsCn {
            get {
                return ResourceManager.GetString("rbBPTopStatsCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Stats, Conservative.
        ///Check for best long-term-results and if you want to go safe.
        ///This mode will get to the best possible offspring steady and surely.
        ///Some offsprings might be worse than in High-Stats-Mode, but that&apos;s the mode you go if you want to have that perfect creature in some generations..
        /// </summary>
        internal static string rbBPTopStatsCnTT {
            get {
                return ResourceManager.GetString("rbBPTopStatsCnTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Stats, Feeling Lucky.
        ///Check for best long-term-results and if you&apos;re feeling lucky. It can be faster to get the perfect creature than in the Top-Stat-Conservative-Mode if you&apos;re lucky.
        ///Some offsprings might be worse than in High-Stats-Mode, but you also have a chance to the best possible offspring..
        /// </summary>
        internal static string rbBPTopStatsTT {
            get {
                return ResourceManager.GetString("rbBPTopStatsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run default Extraction and import file.
        /// </summary>
        internal static string runDefaultExtractionAndImportFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("runDefaultExtractionAndImportFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run default Extraction.
        /// </summary>
        internal static string runDefaultExtractionToolStripMenuItem {
            get {
                return ResourceManager.GetString("runDefaultExtractionToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;as....
        /// </summary>
        internal static string saveAsToolStripMenuItem {
            get {
                return ResourceManager.GetString("saveAsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string saveToolStripMenuItem {
            get {
                return ResourceManager.GetString("saveToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a species to see suggestions for the chosen breeding-mode.
        /// </summary>
        internal static string SelectSpeciesBreedingPlanner {
            get {
                return ResourceManager.GetString("SelectSpeciesBreedingPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Status.
        /// </summary>
        internal static string setStatusToolStripMenuItem {
            get {
                return ResourceManager.GetString("setStatusToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se&amp;ttings….
        /// </summary>
        internal static string settingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("settingsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shocking Tranq Darts.
        /// </summary>
        internal static string ShockingTranqDarts {
            get {
                return ResourceManager.GetString("ShockingTranqDarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slingshot.
        /// </summary>
        internal static string Slingshot {
            get {
                return ResourceManager.GetString("Slingshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slingshot Hits.
        /// </summary>
        internal static string SlingshotHits {
            get {
                return ResourceManager.GetString("SlingshotHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spayed.
        /// </summary>
        internal static string Spayed {
            get {
                return ResourceManager.GetString("Spayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        internal static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp.
        /// </summary>
        internal static string Speed_Abb {
            get {
                return ResourceManager.GetString("Speed_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina.
        /// </summary>
        internal static string Stamina {
            get {
                return ResourceManager.GetString("Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St.
        /// </summary>
        internal static string Stamina_Abb {
            get {
                return ResourceManager.GetString("Stamina_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat-Chart.
        /// </summary>
        internal static string statChart {
            get {
                return ResourceManager.GetString("statChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat Testing.
        /// </summary>
        internal static string statTesting {
            get {
                return ResourceManager.GetString("statTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail.
        /// </summary>
        internal static string Tail {
            get {
                return ResourceManager.GetString("Tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamed.
        /// </summary>
        internal static string tamed {
            get {
                return ResourceManager.GetString("tamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taming.
        /// </summary>
        internal static string Taming {
            get {
                return ResourceManager.GetString("Taming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taming Calculator.
        /// </summary>
        internal static string tamingCalculator {
            get {
                return ResourceManager.GetString("tamingCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taming Effectiveness.
        /// </summary>
        internal static string tamingEffectiveness {
            get {
                return ResourceManager.GetString("tamingEffectiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE.
        /// </summary>
        internal static string TamingEffectiveness_Abb {
            get {
                return ResourceManager.GetString("TamingEffectiveness_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taming Information.
        /// </summary>
        internal static string tamingInfo {
            get {
                return ResourceManager.GetString("tamingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time between mating.
        /// </summary>
        internal static string TimeBetweenMating {
            get {
                return ResourceManager.GetString("TimeBetweenMating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starving of.
        /// </summary>
        internal static string timerStarvingOf {
            get {
                return ResourceManager.GetString("timerStarvingOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wakeup of.
        /// </summary>
        internal static string timerWakeUpOf {
            get {
                return ResourceManager.GetString("timerWakeUpOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time until you can feed all needed food in one go.
        /// </summary>
        internal static string TimeUntilFeedingAllFood {
            get {
                return ResourceManager.GetString("TimeUntilFeedingAllFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time until starving:.
        /// </summary>
        internal static string timeUntilStarving {
            get {
                return ResourceManager.GetString("timeUntilStarving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time until max torpor is depleted.
        /// </summary>
        internal static string TimeUntilTorporDepleted {
            get {
                return ResourceManager.GetString("TimeUntilTorporDepleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string toolStripButtonAddNote {
            get {
                return ResourceManager.GetString("toolStripButtonAddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string toolStripButtonClear {
            get {
                return ResourceManager.GetString("toolStripButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Extractor.
        /// </summary>
        internal static string toolStripButtonCopy2Extractor {
            get {
                return ResourceManager.GetString("toolStripButtonCopy2Extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Tester.
        /// </summary>
        internal static string toolStripButtonCopy2Tester {
            get {
                return ResourceManager.GetString("toolStripButtonCopy2Tester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Expired.
        /// </summary>
        internal static string toolStripButtonDeleteExpiredIncubationTimers {
            get {
                return ResourceManager.GetString("toolStripButtonDeleteExpiredIncubationTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete temp Cr.
        /// </summary>
        internal static string toolStripButtonDeleteTempCreature {
            get {
                return ResourceManager.GetString("toolStripButtonDeleteTempCreature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete currently selected data of the temporary creature.
        /// </summary>
        internal static string toolStripButtonDeleteTempCreatureTT {
            get {
                return ResourceManager.GetString("toolStripButtonDeleteTempCreatureTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Note.
        /// </summary>
        internal static string toolStripButtonRemoveNote {
            get {
                return ResourceManager.GetString("toolStripButtonRemoveNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save values.
        /// </summary>
        internal static string toolStripButtonSaveCreatureValuesTemp {
            get {
                return ResourceManager.GetString("toolStripButtonSaveCreatureValuesTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save entered values until extraction-issue is resolved. This creature cannot be used in other parts of this application until it is properly extracted..
        /// </summary>
        internal static string toolStripButtonSaveCreatureValuesTempTT {
            get {
                return ResourceManager.GetString("toolStripButtonSaveCreatureValuesTempTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tp%.
        /// </summary>
        internal static string topPercentage {
            get {
                return ResourceManager.GetString("topPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This level is in the top {0} % of what you can find..
        /// </summary>
        internal static string topPercentileLevel {
            get {
                return ResourceManager.GetString("topPercentileLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpidity.
        /// </summary>
        internal static string Torpidity {
            get {
                return ResourceManager.GetString("Torpidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Torpidity_Abb {
            get {
                return ResourceManager.GetString("Torpidity_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpor-depletion.
        /// </summary>
        internal static string TorporDepletion {
            get {
                return ResourceManager.GetString("TorporDepletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranquilizer Arrows (Bow).
        /// </summary>
        internal static string TranqArrowsBow {
            get {
                return ResourceManager.GetString("TranqArrowsBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranquilizer Arrows (Crossbow).
        /// </summary>
        internal static string TranqArrowsCrossBow {
            get {
                return ResourceManager.GetString("TranqArrowsCrossBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranquilizer Darts.
        /// </summary>
        internal static string TranqDarts {
            get {
                return ResourceManager.GetString("TranqDarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe.
        /// </summary>
        internal static string Tribe {
            get {
                return ResourceManager.GetString("Tribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as Test.
        /// </summary>
        internal static string tsBtAddAsExtractionTest {
            get {
                return ResourceManager.GetString("tsBtAddAsExtractionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable Creatures.
        /// </summary>
        internal static string unavailableCreaturesToolStripMenuItem {
            get {
                return ResourceManager.GetString("unavailableCreaturesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string viewToolStripMenuItem {
            get {
                return ResourceManager.GetString("viewToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting time after first feeding: ~ {0}.
        /// </summary>
        internal static string waitingAfterFirstFeeding {
            get {
                return ResourceManager.GetString("waitingAfterFirstFeeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careful: this creature could have not enough food, so you might have to feed it before this time to prevent it from starving (check its inventory)!.
        /// </summary>
        internal static string WarningMoreStarvingThanFood {
            get {
                return ResourceManager.GetString("WarningMoreStarvingThanFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        internal static string Weight_Abb {
            get {
                return ResourceManager.GetString("Weight_Abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild.
        /// </summary>
        internal static string wild {
            get {
                return ResourceManager.GetString("wild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild levels, which are considered for breeding.
        /// </summary>
        internal static string wildLevelExplanation {
            get {
                return ResourceManager.GetString("wildLevelExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild-Lvl.
        /// </summary>
        internal static string wildLvl {
            get {
                return ResourceManager.GetString("wildLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With {0} × {1} taming takes {2}.
        /// </summary>
        internal static string WithXFoodTamingTakesTime {
            get {
                return ResourceManager.GetString("WithXFoodTamingTakesTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden Club Hits.
        /// </summary>
        internal static string WoodenClubHits {
            get {
                return ResourceManager.GetString("WoodenClubHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst Possible.
        /// </summary>
        internal static string WorstPossible {
            get {
                return ResourceManager.GetString("WorstPossible", resourceCulture);
            }
        }
    }
}
